version: '3.1'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spotify
    ports:
      - 3307:3306

  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    ports:
      - 6006:80
    depends_on:
      - "db"
    env_file:
      - .env
    volumes:
      - ./:/var/www/html/